const usaHighpoints = [
    {
        state: 'Alabama',
        highpoint: 'Cheaha Mountain', 
        elevation: '2407', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' Alaska',
        highpoint: 'Mount McKinley/Denali', 
        elevation: '20320', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Arizona',
        highpoint: 'Humphreys Peak', 
        elevation: '12633', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Phoenix/Las Vegas'},
        {
        state: ' Arkansas',
        highpoint: 'Mt Magazine/Signal Hill', 
        elevation: '2753', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Oklahoma City'},
        {
        state: ' California',
        highpoint: 'Mount Whitney', 
        elevation: '14494', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Oakland'},
        {
        state: ' Colorado',
        highpoint: 'Mount Elbert', 
        elevation: '14433', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Denver'},
        {
        state: ' Connecticut',
        highpoint: 'Mt Frissell/South Slope', 
        elevation: '2380', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Boston'},
        {
        state: ' Delaware',
        highpoint: 'Ebright Azimuth', 
        elevation: '448', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Philadelphia'},
        {
        state: ' Florida',
        highpoint: 'Britton Hill', 
        elevation: '345', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Destin'},
        {
        state: ' Georgia',
        highpoint: 'Brasstown Bald', 
        elevation: '4784', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' Hawaii',
        highpoint: 'Mauna Kea', 
        elevation: '13796', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Honolulu'},
        {
        state: ' Idaho',
        highpoint: 'Borah Peak', 
        elevation: '12662', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Salt Lake City'},
        {
        state: ' Illinois',
        highpoint: 'Charles Mound', 
        elevation: '1235', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Chicago'},
        {
        state: ' Indiana',
        highpoint: 'Hoosier High Point', 
        elevation: '1257', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Iowa',
        highpoint: 'Hawkeye Point', 
        elevation: '1670', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Kansas',
        highpoint: 'Mount Sunflower', 
        elevation: '4039', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Denver'},
        {
        state: ' Kentucky',
        highpoint: 'Black Mountain', 
        elevation: '4139', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' Louisiana',
        highpoint: 'Driskill Mountain', 
        elevation: '535', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' Maine',
        highpoint: 'Katahdin', 
        elevation: '5268', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Boston'},
        {
        state: ' Maryland',
        highpoint: 'Backbone Mountain', 
        elevation: '3360', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Washington D.C.'},
        {
        state: ' Massachusetts',
        highpoint: 'Mount Greylock', 
        elevation: '3491', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Michigan',
        highpoint: 'Mount Arvon', 
        elevation: '1979', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Chicago'},
        {
        state: ' Minnesota',
        highpoint: 'Eagle Mountain', 
        elevation: '2301', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Chicago'},
        {
        state: ' Mississippi',
        highpoint: 'Woodall Mountain', 
        elevation: '806', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Missouri',
        highpoint: 'Taum Sauk', 
        elevation: '1772', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Kansas City'},
        {
        state: ' Montana',
        highpoint: 'Granite Peak', 
        elevation: '12799', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Nebraska',
        highpoint: 'Panorama Point', 
        elevation: '5424', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Nevada',
        highpoint: 'Boundary Peak', 
        elevation: '13140', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Las Vegas'},
        {
        state: ' NewHampshire',
        highpoint: 'Mount Washington', 
        elevation: '6288', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' NewJersey',
        highpoint: 'High Point', 
        elevation: '1803', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' NewMexico',
        highpoint: 'Wheeler Peak', 
        elevation: '13161', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Albuquerque'},
        {
        state: ' NewYork',
        highpoint: 'Mount Marcy', 
        elevation: '5344', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'New York'},
        {
        state: ' NorthCarolina',
        highpoint: 'Mount Mitchell', 
        elevation: '6684', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: '  NorthDakota',
        highpoint: 'White Butte', 
        elevation: '3506', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Denver'},
        {
        state: ' Ohio',
        highpoint: 'Campbell Hill', 
        elevation: '1550', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Cincinnati'},
        {
        state: ' Oklahoma',
        highpoint: 'Black Mesa', 
        elevation: '4973', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Oklahoma City, Albuquerque'},
        {
        state: ' Oregon',
        highpoint: 'Mount Hood', 
        elevation: '11239', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Pennsylvania',
        highpoint: 'Mount Davis', 
        elevation: '3213', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Washington D.C.'},
        {
        state: ' RhodeIsland',
        highpoint: 'Jerimoth Hill', 
        elevation: '812', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' SouthCarolina',
        highpoint: 'Sassafras Mountain', 
        elevation: '3560', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' SouthDakota',
        highpoint: 'Harney Peak', 
        elevation: '7242', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Denver'},
        {
        state: ' Tennessee',
        highpoint: 'Clingmans Dome', 
        elevation: '6643', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Atlanta'},
        {
        state: ' Texas',
        highpoint: 'Guadalupe Peak', 
        elevation: '8749', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'El Paso'},
        {
        state: ' Utah',
        highpoint: 'Kings Peak', 
        elevation: '13528', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Salt Lake City'},
        {
        state: ' Vermont',
        highpoint: 'Mount Mansfield', 
        elevation: '4393', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Virginia',
        highpoint: 'Mount Rogers', 
        elevation: '5729', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' Washington',
        highpoint: 'Mount Rainier', 
        elevation: '14411', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: ''},
        {
        state: ' WestVirginia',
        highpoint: 'Spruce Knob', 
        elevation: '4863', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Washington D.C.'},
        {
        state: ' Wisconsin',
        highpoint: 'Timms Hill', 
        elevation: '1951', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Chicago'},
        {
        state: ' Wyoming',
        highpoint: 'Gannett Peak', 
        elevation: '13804', 
        hikeLength: '', 
        elevationGain: '', 
        nearestAirport: 'Salt Lake City'},
];

console.log(usaHighpoints[14].elevation);