const usaHighpoints = [
    { "state": "Alabama","highpoint: "Cheaha Mountain","elevation": "2407","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "Alaska","highpoint: "Mount McKinley/Denali","elevation": "20320","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Arizona","highpoint: "Humphreys Peak","elevation": "12633","hike length": "","elevation gain": "","nearest airport": "Phoenix/Las Vegas",
    { "state": "Arkansas","highpoint: "Mt Magazine/Signal Hill","elevation": "2753","hike length": "","elevation gain": "","nearest airport": "Oklahoma City",
    { "state": "California","highpoint: "Mount Whitney","elevation": "14494","hike length": "","elevation gain": "","nearest airport": "Oakland",
    { "state": "Colorado","highpoint: "Mount Elbert","elevation": "14433","hike length": "","elevation gain": "","nearest airport": "Denver",
    { "state": "Connecticut","highpoint: "Mt Frissell/South Slope","elevation": "2380","hike length": "","elevation gain": "","nearest airport": "Boston",
    { "state": "Delaware","highpoint: "Ebright Azimuth","elevation": "448","hike length": "","elevation gain": "","nearest airport": "Philadelphia",
    { "state": "Florida","highpoint: "Britton Hill","elevation": "345","hike length": "","elevation gain": "","nearest airport": "Destin",
    { "state": "Georgia","highpoint: "Brasstown Bald","elevation": "4784","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "Hawaii","highpoint: "Mauna Kea","elevation": "13796","hike length": "","elevation gain": "","nearest airport": "Honolulu",
    { "state": "Idaho","highpoint: "Borah Peak","elevation": "12662","hike length": "","elevation gain": "","nearest airport": "Salt Lake City",
    { "state": "Illinois","highpoint: "Charles Mound","elevation": "1235","hike length": "","elevation gain": "","nearest airport": "Chicago",
    { "state": "Indiana","highpoint: "Hoosier High Point","elevation": "1257","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Iowa","highpoint: "Hawkeye Point","elevation": "1670","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Kansas","highpoint: "Mount Sunflower","elevation": "4039","hike length": "","elevation gain": "","nearest airport": "Denver",
    { "state": "Kentucky","highpoint: "Black Mountain","elevation": "4139","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "Louisiana","highpoint: "Driskill Mountain","elevation": "535","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "Maine","highpoint: "Katahdin","elevation": "5268","hike length": "","elevation gain": "","nearest airport": "Boston",
    { "state": "Maryland","highpoint: "Backbone Mountain","elevation": "3360","hike length": "","elevation gain": "","nearest airport": "Washington D.C.",
    { "state": "Massachusetts","highpoint: "Mount Greylock","elevation": "3491","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Michigan","highpoint: "Mount Arvon","elevation": "1979","hike length": "","elevation gain": "","nearest airport": "Chicago",
    { "state": "Minnesota","highpoint: "Eagle Mountain","elevation": "2301","hike length": "","elevation gain": "","nearest airport": "Chicago",
    { "state": "Mississippi","highpoint: "Woodall Mountain","elevation": "806","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Missouri","highpoint: "Taum Sauk","elevation": "1772","hike length": "","elevation gain": "","nearest airport": "Kansas City",
    { "state": "Montana","highpoint: "Granite Peak","elevation": "12799","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Nebraska","highpoint: "Panorama Point","elevation": "5424","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Nevada","highpoint: "Boundary Peak","elevation": "13140","hike length": "","elevation gain": "","nearest airport": "Las Vegas",
    { "state": "New Hampshire","highpoint: "Mount Washington","elevation": "6288","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "New Jersey","highpoint: "High Point","elevation": "1803","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "New Mexico","highpoint: "Wheeler Peak","elevation": "13161","hike length": "","elevation gain": "","nearest airport": "Albuquerque",
    { "state": "New York","highpoint: "Mount Marcy","elevation": "5344","hike length": "","elevation gain": "","nearest airport": "New York",
    { "state": "North Carolina","highpoint: "Mount Mitchell","elevation": "6684","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "North Dakota","highpoint: "White Butte","elevation": "3506","hike length": "","elevation gain": "","nearest airport": "Denver",
    { "state": "Ohio","highpoint: "Campbell Hill","elevation": "1550","hike length": "","elevation gain": "","nearest airport": "Cincinnati",
    { "state": "Oklahoma","highpoint: "Black Mesa","elevation": "4973","hike length": "","elevation gain": "","nearest airport": "Oklahoma City, Albuquerque",
    { "state": "Oregon","highpoint: "Mount Hood","elevation": "11239","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Pennsylvania","highpoint: "Mount Davis","elevation": "3213","hike length": "","elevation gain": "","nearest airport": "Washington D.C.",
    { "state": "Rhode Island","highpoint: "Jerimoth Hill","elevation": "812","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "South Carolina","highpoint: "Sassafras Mountain","elevation": "3560","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "South Dakota","highpoint: "Harney Peak","elevation": "7242","hike length": "","elevation gain": "","nearest airport": "Denver",
    { "state": "Tennessee","highpoint: "Clingmans Dome","elevation": "6643","hike length": "","elevation gain": "","nearest airport": "Atlanta",
    { "state": "Texas","highpoint: "Guadalupe Peak","elevation": "8749","hike length": "","elevation gain": "","nearest airport": "El Paso",
    { "state": "Utah","highpoint: "Kings Peak","elevation": "13528","hike length": "","elevation gain": "","nearest airport": "Salt Lake City",
    { "state": "Vermont","highpoint: "Mount Mansfield","elevation": "4393","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Virginia","highpoint: "Mount Rogers","elevation": "5729","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "Washington","highpoint: "Mount Rainier","elevation": "14411","hike length": "","elevation gain": "","nearest airport": "",
    { "state": "West Virginia","highpoint: "Spruce Knob","elevation": "4863","hike length": "","elevation gain": "","nearest airport": "Washington D.C.",
    { "state": "Wisconsin","highpoint: "Timms Hill","elevation": "1951","hike length": "","elevation gain": "","nearest airport": "Chicago",
    { "state": "Wyoming","highpoint: "Gannett Peak","elevation": "13804","hike length": "","elevation gain": "","nearest airport": "Salt Lake City",
];

console.log(usaHighpoints[14].elevation);